name: Test FaceTagger Library

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - develop
      - release
  push:
    branches:
      - release
      - develop


jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest